<a href="https://colab.research.google.com/github/IntroComputationalPhysics-UNT/more-on-numpy-Ms091704/blob/main/More_on_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More on NumPy

We have used NumPy already, but there is more that you can do with it, and much of its function is useful in physics modeling. NumPy provides fast, _vectorized_ numerical computations using arrays.

## Review

**Evaluate the following cells**

In [3]:
import numpy as np
np.__version__

'2.0.2'

In [4]:
# explore NumPy
dir(np)[:20] # first 20 entries

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__']

In [5]:
# get help for a specific function
help(np.sin)

Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Trigonometric sine, element-wise.

    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [6]:
# COMPLETE THIS TASK
# Find documentation for np.linspace using '?'
np.linspace?

## Creating Vectors and Matrices

### Creating vectors

In [7]:
v1 = np.array([1, 2, 3])
v2 = np.linspace(0, 1, 5)
v3 = np.arange(0, 10, 2)
v1, v2, v3

(array([1, 2, 3]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0, 2, 4, 6, 8]))

### Creating matrices

In [8]:
A = np.array([[1, 2], [3, 4]])
Z = np.zeros((3,3))
I = np.eye(4)
A, Z, I

(array([[1, 2],
        [3, 4]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

### Indexing and slicing

In [9]:
A[0, 1], A[:, 0], A[1]

(np.int64(2), array([1, 3]), array([3, 4]))

### Random matrices

In [10]:
R = np.random.randn(3,3)
U = np.random.rand(3,3)
R, U

(array([[ 1.00870586,  0.40452749, -0.46426617],
        [-0.03217192,  0.05334141, -0.63686118],
        [-1.67191355, -0.0793964 , -0.82456795]]),
 array([[0.028636  , 0.50912158, 0.0010449 ],
        [0.74826591, 0.90774808, 0.67569282],
        [0.89731121, 0.08839606, 0.85103349]]))

In [11]:
# COMPLETE THIS TASK
# Decompose a 5×5 random matrix into (real) symmetric and antisymmetric parts.
# A symmetric matrix A satisfies A = 0.5*(A + A.T);
# An antisymmetric matrix satisfies A = 0.5*(A - A.T);
# The `.T` attribute finds the transpose of the matrix.
R = np.random.randn(5,5)
U = np.random.randn(5,5)
A = 0.5*(R + R.T)
B = 0.5*(U - U.T)
R, U

(array([[ 1.31235625,  1.78150562,  2.83616713,  2.75455122,  2.14887082],
        [ 0.48699235,  0.28480114, -1.20304758,  0.5182232 , -1.54216249],
        [-0.74209528,  0.00583448,  1.08210244, -0.31667971, -1.61916149],
        [-0.11811964, -1.25390541, -2.27519802,  1.57621902, -0.80503934],
        [ 1.81354799, -0.73959293,  0.66635836, -1.93190926,  1.28255347]]),
 array([[-1.37813338,  1.60987482,  0.64403193,  1.01811581, -0.21986276],
        [-2.29110828,  0.64815671, -0.54629307, -0.29075301, -0.61170143],
        [ 0.69518183,  0.78276405, -0.86948165, -1.63457498,  1.97973269],
        [-0.74583875,  0.91842175, -0.44753086, -0.24131405,  1.27231644],
        [ 0.01062966,  0.69918684,  0.36155197, -0.41578689, -1.12687978]]))

## Operations: *, @, and np.matmul / np.dot

Elementwise and matrix multiplication are treated differently in Numpy.

### Elementwise multiplication (`*`)

In [12]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A * B

array([[ 10,  40],
       [ 90, 160]])

### Matrix multiplication (`@`)

In [13]:
A @ B

array([[ 70, 100],
       [150, 220]])

### Function equivalents for matrix multiplication

In [14]:
np.matmul(A, B), np.dot(A, B)

(array([[ 70, 100],
        [150, 220]]),
 array([[ 70, 100],
        [150, 220]]))

In [15]:
# COMPLETE THESE TASKS
# 1. look into the documentation for `np.matmul`, `np.dot`, `@`, and `*` and explain their difference(s)
  # * is used for element-wise operations and @ or np.matmul for matrx multiplication and np.dot is the general dot product
# 2. create an example/examples to explain their differences

# Define 1D arrays (vectors)
v1 = np.array([1, 2, 3])
v2 = np.array([2, 4, 3])

# Define 2D arrays (matrices)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(f"v1 * v2: {v1 * v2}")
print(f"A * B:\n{A * B}")
print(f"np.dot(v1, v2): {np.dot(v1, v2)}")
print(f"np.dot(A, B):\n{np.dot(A, B)}")
print(f"np.matmul(v1, v2): {np.matmul(v1, v2)}")
print(f"np.matmul(A, B):\n{np.matmul(A, B)}")
print(f"v1 @ v2: {v1 @ v2}")
print(f"A @ B:\n{A @ B}")

v1 * v2: [2 8 9]
A * B:
[[ 5 12]
 [21 32]]
np.dot(v1, v2): 19
np.dot(A, B):
[[19 22]
 [43 50]]
np.matmul(v1, v2): 19
np.matmul(A, B):
[[19 22]
 [43 50]]
v1 @ v2: 19
A @ B:
[[19 22]
 [43 50]]


## Vectorization and Performance

_Vectorization_ means applying operations to whole arrays at once, rather than element by element.

### Loop version -- one element at a time

In [16]:
import math

In [17]:
%%timeit
xs = np.linspace(0, 10, 1_000_000) # here the '_' is used as a visual seperator -- i.e. 1,000,000
ys_loop = np.zeros_like(xs)
for i in range(len(xs)):
  ys_loop[i] = math.sin(xs[i])

270 ms ± 9.13 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Vectorized version

In [18]:
%%timeit
y_vec = np.sin(xs)

NameError: name 'xs' is not defined

In [19]:
# COMPLETE THIS TASK
# ask Gemini about `%%timeit`
  # "when placed at the very beginning of a cell, it measures the execution time of the entire cells content"
  # "it determines the number of loops and repititions needed to acheive a good statistical measure"

In [30]:
# COMPLETE THIS TASK
# create a vectorized function that calculates the total energy (T+U; kinetic + potential energy) of a harmonic oscillator

def total_harmonic_energy(m, k, v, x):
    kinetic_energy = 0.5 * m * v**2
    potential_energy = 0.5 * k * x**2
    total_energy = kinetic_energy + potential_energy
    return total_energy

if __name__ == '__main__':
    mass_array = np.array([1.0, 2.0, 1.5])
    spring_constant_array = np.array([10.0, 8.0, 12.0])
    velocity_array = np.array([2.0, 1.0, 3.0])
    displacement_array = np.array([0.5, 0.8, 0.3])
    energy_array = total_harmonic_energy(mass_array, spring_constant_array,
                                         velocity_array, displacement_array)
    print(f"Total energy (array): {energy_array}")


Total energy (array): [3.25 3.56 7.29]


## Eigenvalues and Eigenvectors

For a matrix $M$, eigenvalues $\lambda$ and eigenvectors $v$ satisfy:
$$ M v = \lambda v $$

In physics, these often realte to characteristic and measurable physical quantities:
* Oscillators → $\lambda$ relates to squared frequencies
* Quantum mechanics → $\lambda$ could be the energy eigenstates
* Rotations → $\lambda$ could define a principal axes

### Here is an example matrix

In [23]:
K = np.array([[ 1,-1, 0]
             ,[-1, 2,-1]
             ,[ 0,-1, 1] ])
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([9.99658224e-17, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
        [-5.77350269e-01,  9.71445147e-17, -8.16496581e-01],
        [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

In [26]:
#COMPLETE THIS TASK
# In the above cell, which eigenvector is associated with which eigenvalue?
# get the eigenvectors
v1 = vecs[:,0]
v2 = vecs[:,1]
v3 = vecs[:,2]
print(f"v1: {v1}")
print(f"v2: {v2}")
print(f"v3: {v3}")

v1: [-0.57735027 -0.57735027 -0.57735027]
v2: [-7.07106781e-01  9.71445147e-17  7.07106781e-01]
v3: [ 0.40824829 -0.81649658  0.40824829]


## Quadratic Form: Diatomic Molecule Model

We can model a diatomic molecule (O$_2$ or N$_2$, for example) as two masses connected by a spring. Motion is restricted to the
bond axis.

The (quadratic) potential energy is: `V = 0.5 * x.T @ K @ x ` where `x = (x1, x2)`, the coordinates of the two atoms.

### Constructing a stiffness/force-constant matrix

In [27]:
k = 2450 # the force constant in an appropriate [energy]/[length] units
K = np.array([[ k,-k]
             ,[-k, k]])
K

array([[ 2450, -2450],
       [-2450,  2450]])

### Diagonalize to find frequencies and normal mode displacement patterns

In [28]:
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([   0., 4900.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

### Vibrational frequencies (ignoring mass)

In [29]:
omega = np.sqrt(vals)
omega

array([ 0., 70.])

### Unitary transformations with eigenvector matrices

If the matrix is not singular, we can find eigenvalues and eigenvectors. The matrix of eigenvectors $U$ forms a unitary transformation.

In [31]:
# COMPLETE THESE TASKS
# Show that U@U.T and U.T@U are 2x2 identity matrices
# Note that normally we would need to use the `.conj().T` attribute to find the conjugate transpose matric, but our matrix is real.
U = vecs
print(f"U@U.T:\n{U@U.T}")

U@U.T:
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]


In [35]:
# COMPLETE THIS TASK
# From the eigenvalue equation M v = λ v, it follows that for U = [v1, v2], then M U = λ U.
# Because λ is diagonal and U.T@U = np.eye(2), it follows that λ = U.T @ K @ U.
# Confirm this behavior.
Lambda_diag = np.diag(vals)
lambda_equals = U.T @ K @ U

print("\nDiagonal matrix Lambda:\n", Lambda_diag)
print("\nU.T @ K @ U:\n", lambda_equals)

# Verify if U.T @ K @ U is equal to the diagonal matrix Lambda
is_UT_K_U_equal_Lambda = np.allclose(lambda_equals, Lambda_diag)
print("\nU.T @ K @ U is equal to Lambda:", is_UT_K_U_equal_Lambda)

# Demonstrate M U = U lambda
M_U = K @ U
U_Lambda = U @ Lambda_diag

print("\nK @ U:\n", M_U)
print("\nU @ Lambda:\n", U_Lambda)

# Verify if M U is equal to U lambda
is_MU_equal_ULambda = np.allclose(M_U, U_Lambda)
print("\nK @ U is equal to U @ Lambda:", is_MU_equal_ULambda)


Diagonal matrix Lambda:
 [[   0.    0.]
 [   0. 4900.]]

U.T @ K @ U:
 [[ 3.94430453e-31  6.65719202e-14]
 [-8.69285906e-14  4.90000000e+03]]

U.T @ K @ U is equal to Lambda: True

K @ U:
 [[-4.70734562e-14 -3.46482323e+03]
 [ 4.70734562e-14  3.46482323e+03]]

U @ Lambda:
 [[    0.         -3464.82322781]
 [    0.          3464.82322781]]

K @ U is equal to U @ Lambda: True


In [38]:
# COMPLETE THIS TASK
# Use the eigenvectors to eigenvalues to interpret the two modes in this model of a diatomic molecule
v1 = U[:, 0]
v2 = U[:, 1]

print("First eigenvector (mode 1):", v1)
print("Second eigenvector (mode 2):", v2)


First eigenvector (mode 1): [-0.70710678 -0.70710678]
Second eigenvector (mode 2): [-0.70710678  0.70710678]
